{% set name = "mrc" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mrc-{{ version }}.tar.gz
  sha256: 69318075eb9cd87f1d7c1f1c9a62bd5179639327430dac68f206467280264c51

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - numpy
    - python >=3.7

test:
  imports:
    - mrc
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tlambert03/mrc
  summary: Read and write .mrc and .dv (deltavision) image file format
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tlambert03
